services:
  # MongoDB
  cadmus-ndp-mongo:
    image: mongo
    container_name: cadmus-ndp-mongo
    # start MongoDB in quiet mode which suppresses most of the log output;
    # comment this out if you want to see the full MongoDB log
    command: mongod --quiet
    # add this if required because of old Ubuntu Kernel issues
    # (https://vedph.github.io/cadmus-doc/deploy/app.html#ubuntu-old-kernel-and-mongodb)
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=1
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - cadmus-ndp-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PostgreSQL
  cadmus-ndp-pgsql:
    image: postgres
    container_name: cadmus-ndp-pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - cadmus-ndp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Cadmus NDP API
  cadmus-ndp-api:
    image: vedph2020/cadmus-ndp-api:16.0.2
    container_name: cadmus-ndp-api
    ports:
      - 5172:8080
    depends_on:
      cadmus-ndp-mongo:
        condition: service_healthy
      cadmus-ndp-pgsql:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ALLOWEDORIGINS__1=*
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-ndp-mongo:27017/{0}
      - CONNECTIONSTRINGS__AUTH=Server=cadmus-ndp-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - CONNECTIONSTRINGS__INDEX=Server=cadmus-ndp-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - CONNECTIONSTRINGS__MOL=Server=cadmus-ndp-pgsql;port=5432;Database=mol;User Id=postgres;Password=postgres;Include Error Detail=True
      - CONNECTIONSTRINGS__TAXOSTORE=Server=cadmus-ndp-pgsql;port=5432;Database=taxo-ndp;User Id=postgres;Password=postgres;Include Error Detail=True
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-ndp-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
      - SEED__DELAY=20
      - MESSAGING__APIROOTURL=http://cadmusapi.azurewebsites.net
      - MESSAGING__APPROOTURL=http://cadmusapi.com/
      - MESSAGING__SUPPORTEMAIL=support@cadmus.com
      # MOL takes about 80 seconds so avoid too many concurrent initializations
      - TAXOSTORE__INITIALIZATIONDELAYSECONDS=120
    networks:
      - cadmus-ndp-network

  # Cadmus NDP App
  cadmus-ndp-app:
    image: vedph2020/cadmus-ndp-app:2.0.0
    container_name: cadmus-ndp-app
    ports:
      - 4200:80
    depends_on:
      - cadmus-ndp-api
    networks:
      - cadmus-ndp-network

networks:
  cadmus-ndp-network:
    driver: bridge
